liip_imagine:
    driver: "gd"

    filter_sets:
            thumbnail_filter_small:
                filters:
                        thumbnail:
                            size: [200, 200]
                            mode: outbound
                            allow_upscale: true
                            
            thumbnail_filter_medium:
                filters:
                        thumbnail:
                            size: [300, 300]
                            mode: outbound
                            allow_upscale: true